---
title: "R Notebook"
output: html_notebook
---

```{r setup}
suppressPackageStartupMessages({
library(PxWebApiData)
library(tidyverse)
library(lubridate)
library(dplyr)
library(stringr)
})
knitr::opts_chunk$set(echo=FALSE, include = FALSE)
```

#Gjennomsnittlig kvadratmeterpris

```{r kommuner}
# vector med relevante kommunenummer
load("knr.Rdata")
```


```{r loade data}
load("knr.Rdata")
```

```{r pm2_raw}
pm2_raw <- ApiData(
urlToData = "06035",
Region = knr,
ContentsCode = "KvPris",
Boligtype = "01",
Tid = c(as.character(2002:2017))
)
```

```{r forenkle navn}
names(pm2_raw)[[1]] <- "desc"
```

```{r data_og_navn}
pm2 <- pm2_raw$dataset %>% 
  select(-Boligtype, -ContentsCode, -NAstatus) %>% 
  rename(
    knr = Region,
    aar = Tid,
    pm2 = value)
pm2 <- pm2 %>% 
  mutate(knavn = pm2_raw$desc$region) %>% 
mutate(
knavn = pm2_raw$desc$region)
```


```{r teste mønster}
load("test_string_tib.Rdata")
# Legg inn regex mønster
moenster <- '\\s*\\([\\d\\s-]*\\d*\\)\\s*$'
test_string_tib %>%
mutate(
knavn = str_replace(knavn, moenster, "")
)
```
```{r endre til nye knavn}
pm2 <- pm2 %>%
mutate(
knavn = str_replace(knavn, moenster, "")
)
```

```{r antall na}
pm2 %>% 
  summarise(across(everything(), ~ sum(is.na(.))))
```


```{r complete cases 2006_1}
pm2fra2006 <- pm2 %>% 
filter(aar >= 2006) %>% 
pivot_wider(
  names_from = aar,
  values_from = pm2,
)
```


Complete cases i perioden 2006-2017: 
```{r complete cases 2006_2}
pm2fra2006 %>%
  complete.cases() %>% 
  sum()
```


```{r complete cases 2008_1}
pm2fra2008 <- pm2 %>% 
filter (aar >= 2008) %>% 
pivot_wider(
  names_from = aar,
  values_from = pm2,
)
```

Complete cases i perioden 2008-2017: 
```{r complete cases 2008_2}
pm2fra2008 %>%
  complete.cases() %>% 
  sum()
```
```{r}
pm2 <- pm2 %>% 
 left_join(pm2fra2008,
           by = c("knr", "knavn"))
na.omit(pm2)
```


```{r rydde}
# Time to clean up
rm(test_string_tib, pm2_raw, pmfra2006)
```


#Befolkning, hente data fra SSB

```{r fra ssb ya}
pop_08_17_ya_raw <- ApiData (
  urlToData = "07459",
  Region = knr,
  Kjonn = c(1, 2),
  Alder = list("agg:TredeltGrupperingB2",
                 c("F20-64")),
  Tid = c(as.character(2008:2017))
) $dataset %>% 
  select(-ContentsCode, -Alder)
```

```{r utvidelse av ya}
pop_08_17_ya <- pop_08_17_ya_raw %>%
  pivot_wider(
    id_cols = c(Region, Tid),
    names_from = Kjonn,
    names_prefix = "sex",
    values_from = value
 )
```

```{r Legge inn korrekte navn ya}
names(pop_08_17_ya)[[1]] <- "knr"
names(pop_08_17_ya)[[2]] <- "aar"
names(pop_08_17_ya)[[3]] <- "ya_menn"
names(pop_08_17_ya)[[4]] <- "ya_kvinner"

```

```{r Lager en total av ya}
pop_08_17_ya <- pop_08_17_ya %>% 
  mutate(ya_total = ya_menn + ya_kvinner)
names(pop_08_17_ya)[[5]] <- "ya_total"
```

```{r Antall observasjoner ya}
dim(pop_08_17_ya)
```

```{r navn ya}
names(pop_08_17_ya)
```

```{r fra ssb hele befolkning}
pop_08_17_raw <- ApiData (
  urlToData = "07459",
  Region = knr,
  Kjonn = c(1, 2),
  Alder = list("agg:TodeltGrupperingB",
                 c("H17", "H18")),
  Tid = c(as.character(2008:2017))
) $dataset %>% 
  select(-ContentsCode)
```


```{r utvidelse av hele befolkning}
pop_08_17 <- pop_08_17_raw %>%
  pivot_wider(
              names_from = Kjonn,
              values_from = value)
```

```{r Legge inn korrekte navn}
names(pop_08_17)[[1]] <- "knr"
names(pop_08_17)[[2]] <- "alder"
names(pop_08_17)[[3]] <- "aar"
names(pop_08_17)[[4]] <- "menn"
names(pop_08_17)[[5]] <- "kvinner"
```

```{r pivot_wider}
pop_08_17 <- pop_08_17 %>%
pivot_wider(names_from = alder,
            values_from = c(menn, kvinner))
```

```{r endre til menn_t og kvinner_t}
pop_08_17 <- pop_08_17 %>%
  mutate(kvinner_t = kvinner_H17 + kvinner_H18,
         menn_t = menn_H17 + menn_H18) %>%
  mutate(totalt_t = kvinner_t + menn_t) 
```

```{r Endre til riktig}
pop_08_17 <- pop_08_17 %>%
  select(knr, aar, menn_t, kvinner_t, totalt_t)
```


```{r antall observasjoner hele befolkningen}
dim(pop_08_17)
```

```{r navn hele befolkningen}
names(pop_08_17)
```

```{r sammenslåing}
pop_08_17_ya_p <- pop_08_17_ya %>%
  left_join(pop_08_17,
            by = c("knr", "aar"))
```


```{r utregninger til prosent}
pop_08_17_ya_p  <- pop_08_17_ya_p  %>%
mutate(kvinner_ya_p = (ya_kvinner/kvinner_t)*100,
       menn_ya_p = (ya_menn/menn_t)*100,
       totalt_ya_p = (ya_total/totalt_t)*100)
```

```{r velge variabler}
pop_08_17_ya_p  <- pop_08_17_ya_p  %>%
select (knr, aar, menn_ya_p, kvinner_ya_p, totalt_ya_p)
```

```{r oppryddning}
rm(pop_08_17_raw, pop_08_17_ya_raw, pop_08_17, pop_08_17_ya)
```


#Inntektsdesiler






